---
title: "gov50 final project"
author: "Cameron Snowden"
description: "something relating to Appalachia"
output: 
  distill::distill_article:
    self_contained: false
---



## Project thoughts

For this project, I'm interested in writing about something relating to Appalachia. I might look at some intersection of poverty, education, and opiod abuse by county throughout the region. The Appalachian Regional Commission (ARC) has a lot of good public data on these issues, so finding data is doable once I think of a proper research question.

Link to data: https://data.arc.gov/data

## Research Question Proposal

Are unemployment rates causing people to leave Appalachia (i.e. is there a correlation between unemployment rates and population change in Appalachian counties?) I hypothesize that increasing unemployment rates are leading decreases in the population of Appalachian counties. I expect that the availability of jobs in some Appalachian counties is fueling stagnant or increase county population levels, while the lack of availability of jobs in other counties is leading to decreasing county populations in those counties. My sample is comprised of data compiled by the Appalachian Regional Commission (ARC) that analyzes unemployment rates and population change by county across all Appalachian counties. The explanatory variable of interest is the percentage of people in an Appalachian county who are unemployed, and it is measured as a percentage of the county population. The outcome variable of interest is population change in Appalachian counties, and it is measured as a percentage difference between the population of a given county from a given year to the following year. If I observe that counties with increasing unemployment rates over several years see a declining population while counties with a stagnant or decreasing unemployment rate have a stagnant or increasing population, my hypothesis would be supported. However, if I observe that counties with increasing unemployment rates over multiple years have population changes similar to those in counties with stagnant or decreasing unemployment rates over multiple years, my hypothesis would be disproven.

Link to data: https://data.arc.gov/data


